#spring.application.name=gateway
server:
    port: 8000

spring:
    cloud:
        gateway:
            enabled: true
            global cors:
                corsConfigurations:
                    '[/**]':
                        allowedOrigins: "*"
                        allowedMethods:
                            - GET
                            - POST
                            - PUT
                            - DELETE
                        #allowedHeaders:
                          #  - "*"
                        #allowCredentials: true
            routes:
                - id: user-service
                  #uri: lb://user-service
                  uri: http://localhost:8080
                  predicates:
                    - Path=/user/**
                  #filters:
                    #- StripPrefix=1
                - id: auth-service
                  uri: http://localhost:8082
                  predicates:
                    - Path=/auth/**

management:
    endpoints:
        web:
            exposure:
                include: "*"
eureka:
  enabled: false